In [6]:
import torch
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

f= 3 * a**3 - b**2

In [7]:
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [8]:
f.backward(gradient=torch.tensor([1,1]))

In [10]:
print(a.grad)

tensor([36., 81.])


In [13]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [11]:
print(b.grad)

tensor([-12.,  -8.])


In [14]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)