In [1]:
import torch

In [6]:
torch.mps.is_available()

True

In [7]:
torch.mps.device_count()

1

### Tesnors
- a high dimensional array, to be used on CPU or macbook silicon

In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
tensor = torch.Tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
arr * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [14]:
tensor * 5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

In [15]:
arr.sum()

np.int64(21)

In [16]:
tensor.sum()

tensor(21.)

In [18]:
tensor = torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
np.random.random((2,4))

array([[0.12107185, 0.9414178 , 0.18678241, 0.96748378],
       [0.72212599, 0.89915494, 0.81873348, 0.50606407]])

In [23]:
torch.rand(2,4)

tensor([[0.4417, 0.9756, 0.5490, 0.3977],
        [0.3749, 0.4921, 0.9190, 0.4052]])

In [25]:
arr.shape

(2, 3)

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr.device

'cpu'

In [28]:
tensor.shape

torch.Size([2, 3])

In [29]:
tensor.device

device(type='cpu')

In [36]:
arr.to_device('mps')

ValueError: Unsupported device: mps. Only 'cpu' is accepted.

In [33]:
tensor = tensor.to('mps')

In [34]:
tensor.sum()

tensor(21, device='mps:0')

In [35]:
tensor.cpu().numpy()

array([[1, 2, 3],
       [4, 5, 6]])